# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: account.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'account.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raccount.proto\x12\x02pb\x1a\x1egoogle/protobuf/wrappers.proto\"2\n\x07\x41\x63\x63ount\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"@\n\x0fRegisterRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"/\n\x0f\x41\x63\x63ountResponse\x12\x1c\n\x07\x61\x63\x63ount\x18\x01 \x01(\x0b\x32\x0b.pb.Account2\xc9\x01\n\x0e\x41\x63\x63ountService\x12=\n\x08Register\x12\x13.pb.RegisterRequest\x1a\x1c.google.protobuf.StringValue\x12\x37\n\x05Login\x12\x10.pb.LoginRequest\x1a\x1c.google.protobuf.StringValue\x12?\n\nGetAccount\x12\x1c.google.protobuf.UInt64Value\x1a\x13.pb.AccountResponseB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_ACCOUNT']._serialized_start=53
  _globals['_ACCOUNT']._serialized_end=103
  _globals['_REGISTERREQUEST']._serialized_start=105
  _globals['_REGISTERREQUEST']._serialized_end=169
  _globals['_LOGINREQUEST']._serialized_start=171
  _globals['_LOGINREQUEST']._serialized_end=218
  _globals['_ACCOUNTRESPONSE']._serialized_start=220
  _globals['_ACCOUNTRESPONSE']._serialized_end=267
  _globals['_ACCOUNTSERVICE']._serialized_start=270
  _globals['_ACCOUNTSERVICE']._serialized_end=471
# @@protoc_insertion_point(module_scope)
